/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project7;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author cs
 */
public class EnrollCoursesFrame extends javax.swing.JPanel {

    private Student currentStudent ;
    private StudentService service ;
    private Databasef db ;
    private String selectedCourseId = null;
    /**
     * Creates new form EnrollCoursesFrame
     */
    public EnrollCoursesFrame(Student student , StudentService service ,Databasef db ) {
        this.currentStudent = student ;
        this.service = service ;
        this.db = db ;
        initComponents();
        loadAvailableCourses() ;
    }

    private void loadAvailableCourses() {

    // Load all courses from database
    ArrayList<Course> allCourses = Databasef.readCourses();
    ArrayList<User> allUsers = Databasef.readUsers();
    ArrayList<Course> approved = new ArrayList<>();

    // Prepare table model
    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

    model.setRowCount(0);  // clear old rows

    // Fill table with data
    for (Course c : allCourses) {
        
        if (c.getStatus() != Course.Status.APPROVED) {
            continue;  
        }
        
        if (currentStudent.getEnrolledCourses().contains(c.getCourseId())) {
            continue;
        }


        // Get instructor name from users list
        String instructorName = "";
        for (User u : allUsers) {
            if (u.getId().equals(c.getInstructorId())) {
                instructorName = u.getName();
                break;
            }
        }

        model.addRow(new Object[]{
                c.getCourseId(),
                c.getTitle(),
                c.getDescription(),
                instructorName
        });
    }
}

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Id     ", "Title", "Description", "Instructor"
            }
        ));
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Enroll");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Open Lessons");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jButton1)
                .addGap(175, 175, 175)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(0, 147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = jTable1.getSelectedRow();

if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Please select a course.");
    return;
}

String courseId = jTable1.getValueAt(selectedRow, 0).toString();

// TEMP: replace when login is connected
String loggedStudentId = currentStudent.getId();


// Load database
ArrayList<User> allUsers = Databasef.readUsers();
ArrayList<Course> allCourses = Databasef.readCourses();

// Find student
Student student = null;
for (User u : allUsers) {
    if (u instanceof Student && u.getId().equals(loggedStudentId)) {
        student = (Student) u;
        break;
    }
}

if (student == null) {
    JOptionPane.showMessageDialog(this, "Student not found!");
    return;
}

// Check duplicate enrollment
if (student.getEnrolledCourses().contains(courseId)) {
    JOptionPane.showMessageDialog(this, "You are already enrolled in this course.");
    return;
}

// Add course to student
student.getEnrolledCourses().add(courseId);

// Add student to course
for (Course c : allCourses) {
    if (c.getCourseId().equals(courseId)) {
        c.addStudent(student);
        break;
    }
}

// Save
Databasef.writeUsers(allUsers);
Databasef.writeCourses(allCourses);

JOptionPane.showMessageDialog(this, "Enrolled Successfully!");

loadAvailableCourses();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course first.");
        return;
    }

    String courseId = jTable1.getValueAt(selectedRow, 0).toString();
    LessonViewerFrame lv = new LessonViewerFrame(courseId, currentStudent, service, db);
    
    lv.setVisible(true);

    SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         StudentDashboardFrame dashboard = new StudentDashboardFrame(currentStudent , service , db);
        dashboard.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
    if (row == -1) return; 
    
    selectedCourseId = jTable1.getValueAt(row, 0).toString();
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
