/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project7;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class LessonViewerFrame extends javax.swing.JPanel {

    
    private Student currentStudent;
    private StudentService service;
    private Databasef db;
    private String courseId;
     
    
    
 
    
    public LessonViewerFrame(String courseId, Student student, StudentService service, Databasef db) {
        this.courseId = courseId;
        this.currentStudent = student;
        this.service = service;
        this.db = db;

        initComponents();
        loadLessons();
    }
    
    
    
    public LessonViewerFrame() {
        initComponents();
    }

    
    private void loadLessons() {

    // Load all courses
    ArrayList<Course> allCourses = Databasef.readCourses();

    // Find selected course
    Course selectedCourse = null;

    for (Course c : allCourses) {
        if (c.getCourseId().equals(courseId)) {
            selectedCourse = c;
            break;
        }
    }

    if (selectedCourse == null) {
        JOptionPane.showMessageDialog(this, "Course not found!");
        return;
    }

    // Load student for progress check
    ArrayList<User> users = Databasef.readUsers();
    Student currentStudent = null;

    for (User u : users) {
        if (u instanceof Student) {
            currentStudent = (Student) u;
            break;
        }
    }

    // Fill table model
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    for (Lesson lesson : selectedCourse.getLessons()) {

        boolean completed = false;

        if (currentStudent != null &&
            currentStudent.getProgress().containsKey(courseId)) {

            completed =
                currentStudent.getProgress()
                    .get(courseId)
                    .contains(lesson.getLessonId());
        }

        model.addRow(new Object[]{
            lesson.getLessonId(),
            lesson.getTitle(),
            completed ? "Yes" : "No"
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lesson ID", "Lesson Title", "completeness"
            }
        ));
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jButton1)
                .addContainerGap(179, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    StudentDashboardFrame dashboard = new StudentDashboardFrame(currentStudent, service , db);
    dashboard.setVisible(true);
    SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
