/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project7;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class OpenLessonFrame extends javax.swing.JPanel {

    /**
     * Creates new form OpenLessonFrame
     */
    
    
    private String courseId;
    private Student student;
    private StudentService service ;
    private Databasef db;
    
    
    public OpenLessonFrame(String courseId, Student student, StudentService service, Databasef db) {
    initComponents();
    this.courseId = courseId;
    this.student = student;
    this.service = service;
    this.db = db;

    loadLessons();
}
    
    
    private void loadLessons() {
    ArrayList<Course> courses = Databasef.readCourses();

    DefaultTableModel model = (DefaultTableModel) lessonsTable.getModel();
    model.setRowCount(0);

    for (Course c : courses) {
        if (c.getCourseId().equals(courseId)) {

            for (Lesson l : c.getLessons()) {
                
                boolean completed = student.hasCompletedLesson(courseId, l.getLessonId());

                model.addRow(new Object[]{
                    l.getLessonId(),
                    l.getTitle(),
                    l.getContent(),
                    completed ? "✔️ Yes" : "❌ No",
                    "Open"
                });
            }
        }
    }
}
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lessonsTable = new javax.swing.JTable();

        lessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lesson ID", "Lesson Title", "content", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lessonsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lessonsTable;
    // End of variables declaration//GEN-END:variables
}
