/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project7;

import java.util.ArrayList;

/**
 *
 * @author youssef
 */
public class QuizPanel extends javax.swing.JPanel {
    private Student currentstudent;
    private Databasef db;
    private Lesson selectedLesson;
    private int currentQuestionIndex = 0;
    private ArrayList<Question> questions;
    private ArrayList<String> selectedAnswers;
    private QuizAttempt currentAttempt;
    private StudentService service;
    private Course selectedCourse;
    /**
     * Creates new form QuizPanel
     */
    public QuizPanel(Student currentstudent,Lesson selectedLesson,Databasef db,StudentService service,Course selectedCourse) {
        this.currentstudent=currentstudent;
        this.db=db;
        this.service=service;
        this.selectedLesson=selectedLesson;
        this.questions=this.selectedLesson.getQuiz().getQuestions();
        this.selectedAnswers = new ArrayList<>();
        for(int i=0; i<questions.size(); i++){
        selectedAnswers.add(null);
    }
         this.currentAttempt = db.startOrGetNewAttempt(currentstudent.getId(), selectedLesson.getQuiz().getQuizId());
         this.selectedCourse=selectedCourse;

        
        initComponents();
        updateQuestionDisplay();
        updateButtonsVisibility();
    }
    
    private void updateQuestionDisplay() {
    Question q = questions.get(currentQuestionIndex);
    
    jTextArea1.setText((currentQuestionIndex + 1) + ". " + q.getText());
    
    jRadioButton1.setText(q.getChoices().get(0));
    jRadioButton2.setText(q.getChoices().get(1));
    jRadioButton3.setText(q.getChoices().get(2));
    jRadioButton4.setText(q.getChoices().get(3));

    buttonGroup1.clearSelection(); // نمسح أي اختيار قديم
    
    // لو الطالب اختار إجابة قبل كده نحددها
    String ans = selectedAnswers.get(currentQuestionIndex);
    if(ans != null){
        if(ans.equals(q.getChoices().get(0))) jRadioButton1.setSelected(true);
        else if(ans.equals(q.getChoices().get(1))) jRadioButton2.setSelected(true);
        else if(ans.equals(q.getChoices().get(2))) jRadioButton3.setSelected(true);
        else if(ans.equals(q.getChoices().get(3))) jRadioButton4.setSelected(true);
    }
}
    private void updateButtonsVisibility() {
    int lastIndex = questions.size() - 1;
    jButton2.setVisible(currentQuestionIndex > 0); // Previous
    jButton1.setVisible(currentQuestionIndex < lastIndex); // Next
    jButton3.setVisible(currentQuestionIndex == lastIndex); // Submit
}
    
    private void saveSelectedAnswer() {
    Question q = questions.get(currentQuestionIndex);
    if(jRadioButton1.isSelected()) selectedAnswers.set(currentQuestionIndex, q.getChoices().get(0));
    else if(jRadioButton2.isSelected()) selectedAnswers.set(currentQuestionIndex, q.getChoices().get(1));
    else if(jRadioButton3.isSelected()) selectedAnswers.set(currentQuestionIndex, q.getChoices().get(2));
    else if(jRadioButton4.isSelected()) selectedAnswers.set(currentQuestionIndex, q.getChoices().get(3));
}
    private int calculateScore() {
    int correctCount = 0;
    for (int i = 0; i < questions.size(); i++) {
        String selected = selectedAnswers.get(i);
        if (selected != null && selected.equals(questions.get(i).getCorrectAnswer())) {
            correctCount++;
        }
    }
    return  correctCount; // ممكن تحسب نسبة لو عايز
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Solve Quiz");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton2");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton3");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("jRadioButton4");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Previous");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(728, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addGap(309, 309, 309))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(486, 486, 486)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(364, 364, 364))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(413, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saveSelectedAnswer();
    if(currentQuestionIndex < questions.size() - 1){
        currentQuestionIndex++;
        updateQuestionDisplay();
        updateButtonsVisibility();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        saveSelectedAnswer();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        saveSelectedAnswer();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        saveSelectedAnswer();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        saveSelectedAnswer();
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        saveSelectedAnswer();
    if(currentQuestionIndex > 0){
        currentQuestionIndex--;
        updateQuestionDisplay();
        updateButtonsVisibility();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         saveSelectedAnswer();

    // 2) نحسب السكور
    int finalScore = calculateScore();
    boolean passed=false ;
            if(finalScore>=selectedLesson.getQuiz().getQuestions().size())
                passed=true;
    
   Student student = Student.getStudentById(currentstudent.getId());
   
   student.recordQuizResult(selectedCourse.getCourseId(),selectedLesson.getLessonId(), finalScore, passed);


    // 3) نحفظ السكور في الملف باستخدام نفس attempt اللي اتفتح من الأول
    db.saveAttemptScore(currentAttempt.getAttemptId(), finalScore);

    // 4) نفتح صفحة النتيجة
    ResultPanel resultPanel = new ResultPanel(finalScore, questions, selectedAnswers,service,currentstudent,db);

    // 5) نخليها تبان
    javax.swing.JFrame topFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
    topFrame.dispose(); // يقفل نافذة الامتحان الحالية

    // 6) نعرض النتيجة في نافذة جديدة
    javax.swing.JFrame resultFrame = new javax.swing.JFrame("Quiz Result");
    resultFrame.setContentPane(resultPanel);
    resultFrame.pack();
    resultFrame.setLocationRelativeTo(null); // يظهر في النص
    resultFrame.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
