/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package project7;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import java.awt.BorderLayout;





/**
 *
 * @author DELL
 */
public class ViewInsightsFrame extends javax.swing.JPanel {

    private Instructor instructor;
    private Databasef db;

    
    
    public ViewInsightsFrame(Instructor instructor, Databasef db) {
        this.instructor = instructor;
        this.db = db;

        initComponents();
        loadInsights();
    }
    
    
    
    public ViewInsightsFrame() {
        initComponents();
    }

    
    
    private double calculateCourseCompletion(Course course) {
    int totalStudents = course.getStudents().size();
    if (totalStudents == 0) return 0;

    int completedCount = 0;

    for (Student st : course.getStudents()) {
        if (st.hasCompletedCourse(course)) {
            completedCount++;
        }
    }

    return (completedCount / (double) totalStudents) * 100.0;
}
    
    
    private void displayAllCoursesChart(ArrayList<Course> courses) {

    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    for (Course c : courses) {
        double comp = calculateCourseCompletion(c);
        dataset.addValue(comp, "Completion %", c.getTitle());
    }

    JFreeChart barChart = ChartFactory.createBarChart(
            "Course Completion",
            "Course",
            "Percentage",
            dataset
    );

    ChartPanel chart = new ChartPanel(barChart);

    chartPanel.removeAll();
chartPanel.add(chart, BorderLayout.CENTER);
chartPanel.revalidate();
chartPanel.repaint();
}
    
    
    
    private void loadInsights() {

    ArrayList<Course> courses = Databasef.readCourses();
    ArrayList<User> users = Databasef.readUsers();

    int totalStudents = 0;
    double totalCompletion = 0;
    double totalQuizScore = 0;
    int quizCount = 0;

   
    
    
    DefaultTableModel model = (DefaultTableModel) quizTable.getModel();
    model.setRowCount(0);

    for (Course c : courses) {

        totalStudents += c.getStudents().size();

        for (Student st : c.getStudents()) {
            if (st.hasCompletedCourse(c)) totalCompletion++;
        }

        // ====== QUIZ TABLE ======
        for (Lesson lesson : c.getLessons()) {
            for (Student st : c.getStudents()) {

                QuizResults qr = st.getQuizResults().get(lesson.getLessonId());
                if (qr != null) {
                    model.addRow(new Object[]{
                            lesson.getTitle(),
                            qr.getScore() + "%",
                            qr.isPassed() ? "Yes" : "No",
                            qr.getAttempts()
                    });

                    totalQuizScore += qr.getScore();
                    quizCount++;
                }
            }
        }
    }

    // ======= SUMMARY =======
    if (totalStudents > 0) {
        avgCompletionLabel.setText(String.format("%.2f%%", (totalCompletion / totalStudents) * 100));
    }

    totalStudentsLabel.setText(String.valueOf(totalStudents));

    if (quizCount > 0) {
        avgQuizLabel.setText(String.format("%.2f%%", totalQuizScore / quizCount));
    }

    // ======= DISPLAY CHART =======
    displayAllCoursesChart(courses);
}
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        quizTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        totalStudentsLabel = new javax.swing.JLabel();
        avgCompletionLabel = new javax.swing.JLabel();
        avgQuizLabel = new javax.swing.JLabel();

        chartPanel.setBackground(new java.awt.Color(255, 255, 255));
        chartPanel.setLayout(new java.awt.BorderLayout());

        quizTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lesson", "Average %", "Pass Rate %", "Attempts"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(quizTable);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        totalStudentsLabel.setText("Total Students");

        avgCompletionLabel.setText("Average Completion");

        avgQuizLabel.setText("Average Quiz Score");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalStudentsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avgCompletionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avgQuizLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(totalStudentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(avgCompletionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(avgQuizLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(chartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(chartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avgCompletionLabel;
    private javax.swing.JLabel avgQuizLabel;
    private javax.swing.JPanel chartPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable quizTable;
    private javax.swing.JLabel totalStudentsLabel;
    // End of variables declaration//GEN-END:variables
}
